project:
  type: book
  output-dir: docs

execute:
  freeze: true  

brand: _brand.yml

lang: de


book:
  title: "IfSG & ÖGD"
  subtitle: "Unterricht für den ÖGD"
  author: "Jakob Schumacher"
  date: last-modified
  description: Dies ist ein Mini-Lehrbuch für den Öffentlichen Gesundheitsdienst (ÖGD). Es beinhaltet Hintergrundinformationen zum Infektionsschutzgesetz (IfSG) und zum Meldewesen.
  search: true
  output-file: "Mini-Lehrbuch_Infektionsschutzgesetz"
  favicon: images/logo.png
  sidebar:
    style: floating
    logo: images/logo.png
    background: light
    collapse-level: 1
  repo-url: https://github.com/jakobschumacher/ifsg
  downloads: [pdf, epub]
  page-footer:
    left: Das Infektionsschutzgesetz - Unterrichtsmaterial für den ÖGD - von Jakob Schumacher
    right: 
      - text: "Buch erstellt mit Quarto"
        href: https://quarto.org/
      - text: "Lizenz: MIT"
        href: LICENSE.html
      - text: "Impressum"
        href: about.html
  chapters:
    - index.qmd
    - part: "Grundlagen"
      chapters:
        - content/grundlagen/ifsg_einordnung.qmd
        - content/grundlagen/ifsg_praegung.qmd
        - text: Überblick
          file: content/grundlagen/ifsg_ueberblick.qmd
        - text: Erstellende
          file: content/meldewesen/meld_bestimmer.qmd
        - text: Exkurs Begriffe
          file: content/meldewesen/meld_begriffe.qmd  
    - part: "Einleitungsparagraphen"
      chapters:
        - text: § 1
          file: content/paragraphen/par_1.qmd
        - text: § 3
          file: content/paragraphen/par_3.qmd
        - text: § 4
          file: content/paragraphen/par_4.qmd
    - part: "Meldewesen"
      chapters:
        - text: Schaubild
          file: content/meldewesen/meld_schaubild.qmd
        - text: § 6
          file: content/paragraphen/par_6.qmd
        - text: § 7
          file: content/paragraphen/par_7.qmd
        - text: § 8
          file: content/paragraphen/par_8.qmd
        - text: § 12
          file: content/paragraphen/par_12.qmd
    - part: "Verhütung"
      chapters:
        - text: § 16
          file: content/paragraphen/par_16.qmd
        - text: § 20
          file: content/paragraphen/par_20.qmd
        - text: § 23
          file: content/paragraphen/par_23.qmd
        - text: § 23a
          file: content/paragraphen/par_23a.qmd
    - part: "Bekämpfung"
      chapters:
        - text: § 25
          file: content/paragraphen/par_25.qmd
        - text: § 28
          file: content/paragraphen/par_28.qmd
    - part: "Einrichtungen"
      chapters:
        - text: § 34
          file: content/paragraphen/par_34.qmd
        - text: § 35
          file: content/paragraphen/par_35.qmd
        - text: § 36
          file: content/paragraphen/par_36.qmd
        - text: § 73
          file: content/paragraphen/par_73.qmd
    - part: "Die Flughafenübung"
      chapters:
        - file: content/uebungen/ueb_flughafen.qmd
        - text: Übung zum Meldewesen
          file: content/uebungen/ueb_meldungen.qmd
    - part: "Diskussion"
      chapters:
        - text: Wieso sind unsere Schreiben so unverständlich?
          file: content/diskussion/disk_unverstaendlich.qmd
        - content/diskussion/disk_praevention.qmd
        - content/diskussion/disk_meldemoral.qmd


format:
  epub: default
  html:
    theme: Zephyr
    toc: false
    number-sections: false
  pdf: 
    documentclass: scrbook
    classoption: [oneside, 11pt, a4paper]
    geometry:
      - inner=2cm
      - outer=2cm
      - top=2cm
      - bottom=2cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded

    
